#!/usr/bin/env bash
# Display the subdomains and information
# shellcheck version
if [ "$2" ]; then
	dig "$2.$1" | awk '/;; ANSWER SECTION:/ { getline; split($1,a,".");print "The subdomain " a[1],"is a "$4,"record and points to "$5}'
else
	for s in "www" "lb-01" "web-01" "web-02"
	do
		dig "$s.$1" | awk '/;; ANSWER SECTION:/ { getline; split($1,a,".");print "The subdomain " a[1],"is a "$4,"record and points to "$5}'
	done
fi
