#!/usr/bin/env bash
# install nginX
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i '0,/listen.*/s/listen.*/listen 80 default_server;/' /etc/nginx/sites-enabled/default
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n"
sudo sed -i "42i $redirect" /etc/nginx/sites-available/default
sudo service nginx restart
