#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt-get update
sudo apt-get -y install nginx
res="\\\t\tadd_header X-Served-By '$HOSTNAME';\n"
sudo sed -i "55i $res" /etc/nginx/sites-available/default
sudo service nginx restart
