#!/usr/bin/env bash
# installing the load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*
frontend="\nfrontend haproxynode\n\tbind *:80\n\tdefault_backend back_nodes\n"
backend="backend back_nodes\n\tbalance roundrobin\n\tserver 764-web-01 104.196.1.139 check\n\tserver 764-web-02 35.227.123.185 check\n"
echo -e $frontend | sudo tee --append /etc/haproxy/haproxy.cfg
echo -e $backend | sudo tee --append /etc/haproxy/haproxy.cfg
sudo service haproxy restart
