#!/usr/bin/env bash
# installing the load balancer
sudo apt-get update
sudo apt-get install -y haproxy
echo "
frontend 764-frontend
    bind *:80
    default_backend 764-backend

backend 764-backend
    balance roundrobin
    option forwardfor 
    server 764-web-01 104.196.1.139
    server 764-web-02 35.227.123.185
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
