#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get -y install nginx
sudo awk 'BEGIN { print "Holberton School" > "/var/www/html/index.nginx-debian.html" }'
sudo service nginx restart 
