#!/usr/bin/env bash
# Fixing the port 80
sudo service nginx start
sudo sed -i '0,/listen [^0-9].*/s/listen [0-9].*/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sudo pkill -o nginx
sudo service nginx restart
