#!/usr/bin/env bash
# This script  that loops from 1 to 10 and 4th or 8th position 

i=1
while ((i <= 100)); do
if (( i % 3 == 0 && i % 5 == 0 )); then
echo "FizzBuzz"
elif (( i % 3 == 0 )); then
echo "Fizz"
elif (( i % 5 == 0 )); then
echo "Buzz"
else
echo $i 
fi
((i++))
done
