#!/usr/bin/env bash
# This script  that loops from 1 to 10 and 4th or 8th position 

i=0
while ((i < 10)); do
if [[ $i == '3' ]]; then
echo "bad luck"
elif [[ $i == '7' ]]; then
echo "good luck"
else
echo "Holberton School"
fi
((i++))
done
