#!/usr/bin/env bash
# run Nginix as nginx user

sudo pkill -9 apache2
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 744 /etc/nginx/nginx.conf
sudo sed -i '0,/listen [^0-9].*/s/listen [0-9].*/listen 8080 default_server;/' /etc/nginx/sites-enabled/default
sudo service nginx restart
