#!/usr/bin/env bash
# run Nginix as nginx user
sudo pkill -9 apache2
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo chmod 744 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
